import { Providers } from "@/redux/provider"
import Loader from "@/component/core/Loader"


import "@/style/style.map.scss"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <Loader />
          {children}
        </Providers>
      </body>
    </html>
  )
}
